"use client";
import React from "react";
import { SVGIcon } from "@/lib/types/interfaces/common.interface";

// GenerationJobIcon.tsx
export default function GenerationJobsIcon({
  className,
  width,
  height,
  color,
}: SVGIcon) {
  return (
    <svg
      className={className}
      viewBox="0 0 32 32"
      fill="none"
      width={width}
      height={height}
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M23,15H9c-1.1,0-2-0.9-2-2V4c0-1.1,0.9-2,2-2h14c1.1,0,2,0.9,2,2v9C25,14.1,24.1,15,23,15z"
        color={color}
        className="stroke-current"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
      />
      <line
        x1="7"
        y1="6"
        x2="25"
        y2="6"
        color={color}
        className="stroke-current"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
      />
      <line
        x1="11"
        y1="5"
        x2="11"
        y2="2"
        color={color}
        className="stroke-current"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
      />
      <rect
        x="3"
        y="23"
        width="6"
        height="6"
        color={color}
        className="stroke-current"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
      />
      <rect
        x="13"
        y="23"
        width="6"
        height="6"
        color={color}
        className="stroke-current"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
      />
      <rect
        x="23"
        y="23"
        width="6"
        height="6"
        color={color}
        className="stroke-current"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
      />
      <polyline
        points="6,23 6,19 26,19 26,23"
        color={color}
        className="stroke-current"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
      />
      <line
        x1="16"
        y1="15"
        x2="16"
        y2="23"
        color={color}
        className="stroke-current"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
      />
    </svg>
  );
}
